
services:
  # Laravel App Service
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: airbooking_backend
    restart: unless-stopped
    working_dir: /var/www/html
    volumes:
      - .:/var/www/html
    environment:
      - DB_CONNECTION=pgsql
      - DB_HOST=postgres
      - DB_PORT=5432
      - DB_DATABASE=airbooking-db
      - DB_USERNAME=postgres
      - DB_PASSWORD=root
    depends_on:
      - postgres

  # PostgreSQL Service
  postgres:
    image: postgres:15
    container_name: airbooking-postgres
    restart: unless-stopped
    environment:
      POSTGRES_DB: airbooking-db
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: root
    ports:
      - "5432:5432"
    volumes:
      - postgres-data:/var/lib/postgresql/data

  # Nginx Service
  webserver:
    image: nginx:alpine
    container_name: laravel-webserver
    restart: unless-stopped
    ports:
      - "80:80"
    volumes:
      - .:/var/www/html
      - ./nginx.conf:/etc/nginx/conf.d/default.conf
    depends_on:
      - app

# Volumes
volumes:
  postgres-data: